name: SonarCloud (.NET + Coverage)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Sonar begin
        run: >
          dotnet sonarscanner begin
          /k:"varunusstaffing043-sketch_TestApp"
          /o:"varunusstaffing043-sketch"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Restore
        run: dotnet restore TestApp.sln

      - name: Build
        run: dotnet build TestApp.sln --no-restore --configuration Release

      - name: Test with coverage
        run: dotnet test TestApp.sln --no-build --configuration Release --collect "XPlat Code Coverage;Format=opencover"

      - name: Sonar end
        run: dotnet sonarscanner end
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
