name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for SonarCloud

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Match your SDK

      - name: Install dependencies
        run: dotnet restore TestApp.sln

      - name: Build solution
        run: dotnet build TestApp.sln --no-restore

      - name: Run tests
        run: dotnet test TestApp.Tests/TestApp.Tests.csproj --no-build --collect:"Code Coverage"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: varunusstaffing043-sketch_.net-test-
          SONAR_ORGANIZATION: varunusstaffing043-sketch
